before_script:

after_script:

stages:
  - build
  - test
  - deploy
  
job_build:
  stage: build
  script:
    - true

job_test:
  stage: test
  script:
    - true

job_deploy:
  stage: deploy
  script:
    - true
